/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2020u.lab02;

public class Simple {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Simple().getGreeting());
    }
}
