version: "3.9"
services:
  csci2020u:
      build: .
      secrets:
        - source: host_ssh_key
          target: /root/.ssh/id_ed25519
          uid: "0"
          gid: "0"
          mode: 0600
secrets:
  host_ssh_key:
    file: ~/.ssh/id_ed25519
