/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2020u.lab03;

import org.junit.Test;
import static org.junit.Assert.*;

public class CSVDemoTest {
    @Test public void testCSVDemoHasAGreeting() {
        CSVDemo classUnderTest = new CSVDemo();
        assertNotNull("csvdemo should have a greeting", classUnderTest.getGreeting());
    }
}
