/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csci2020u.lab02;

import org.junit.Test;
import static org.junit.Assert.*;

public class SimpleTest {
    @Test public void testSimpleHasAGreeting() {
        Simple classUnderTest = new Simple();
        assertNotNull("simple should have a greeting", classUnderTest.getGreeting());
    }
}
